name: Publish Docker image

on:
  push:
    tags:
      - v*
    branches:
      - create-another-image-from-workspace-full
  # release:
  #   types: [published]

jobs:
  docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # workspace-image: [base, full]
        images:
          - gingerich/gitpod-devspace
          - gingerich/gitpod-devspace-full
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   if: ${{ matrix.workspace-image == 'base' }}
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: gingerich/gitpod-devspace
      #     tags: |
      #       type=semver,pattern={{version}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # if: ${{ matrix.workspace-image == 'full' }}
        uses: docker/metadata-action@v3
        with:
          # images: gingerich/gitpod-devspace${{ (matrix.workspace-image == 'full' && '-full') || '' }}
          images: ${{ matrix.images }}
          # images: |
          #   ${{ matrix.workspace-image == 'base' && 'gingerich/gitpod-devspace' }}
          #   ${{ matrix.workspace-image == 'full' && 'gingerich/gitpod-devspace-full' }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            KUBECTL_VERSION=v1.23.4
            ${{ endsWith(matrix.images, 'full') && 'GITPOD_IMAGE=gitpod/workspace-full:latest' }}